services:
  webtrader:
    image: 100.89.24.22:4567/wangzhijun/vnpy:latest
    container_name: ${COMPOSE_CONTAINER_NAME:-vnpy-webtrader}
    ports:
      - "${WEB_PORT:-8080}:8080"
    restart: unless-stopped
